# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vulnerable SSH Server in'a Can ( well, a VM ).
Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-SHELL
    sudo su root
    # for fun
    sed -i -e 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    service sshd restart
  SHELL
end
